baseURL = "https://ahmedprog.github.io//"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-resume"

[params]
    firstName = "Ahmed"
    lastName = "Nasser"
    address = "Giza, Egypt"
    phone = "02001110553564"
    contactNote = "Back-end Developer" #used in QR code only
    profileImage = "img/TechChat.png"
    email = "ahmed.6nasser@gmail.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = true

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/a-nasser6/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ahmedprog"


[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/9103476/ahmed-nasser"
    icon = "stack-overflow" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.



[params.google.analytics]
    trackerID = "XX-123446-01"

[outputs] #only required for search
    home = ["HTML", "JSON"]
